# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginAndRegistration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=500)),
                ('speaker', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quoteAdder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoteAdder', to='loginAndRegistration.User')),
                ('quoteFavoriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoteFavoriter', to='loginAndRegistration.User')),
            ],
        ),
    ]
