# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegistration', '0001_initial'),
        ('beltThreeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_favoriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoteFavoriter', to='loginAndRegistration.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quoteFavoriter',
        ),
        migrations.AddField(
            model_name='favoritequote',
            name='quote_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoteId', to='beltThreeApp.Quote'),
        ),
    ]
